//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetToolkit.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetToolkit.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;MyCustomEntity1 Value18=&quot;This is an attribute value&quot; Value19=&quot;10&quot; Value20=&quot;Ctor argument1&quot; Value26=&quot;0&quot; Value30=&quot;30&quot; Value31=&quot;31&quot;&gt;
        ///  &lt;Value0&gt;Value0&lt;/Value0&gt;
        ///  &lt;Value1&gt;1&lt;/Value1&gt;
        ///  &lt;Value2&gt;2&lt;/Value2&gt;
        ///  &lt;MyCustomValue3&gt;3&lt;/MyCustomValue3&gt;
        ///  &lt;MyCustomValue4&gt;
        ///    &lt;Int32&gt;1&lt;/Int32&gt;
        ///    &lt;Int32&gt;2&lt;/Int32&gt;
        ///    &lt;Int32&gt;3&lt;/Int32&gt;
        ///    &lt;Int32&gt;4&lt;/Int32&gt;
        ///  &lt;/MyCustomValue4&gt;
        ///  &lt;Value5&gt;
        ///    &lt;String&gt;11 11&lt;/String&gt;
        ///    &lt;String&gt;22 22&lt;/String&gt;
        ///  &lt;/Value5&gt;
        ///  &lt;MyCustomColectionValue6&gt;
        ///    &lt;Int32&gt;1&lt;/Int32&gt;
        ///    &lt;Doubl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MySerializableEntityTest1Data {
            get {
                return ResourceManager.GetString("MySerializableEntityTest1Data", resourceCulture);
            }
        }
    }
}
